id: ID4D310F4
ocr_import_info:
  timestamp: '2023-10-07T14:08:05.346880+00:00'
  batch_id: batch-6be9
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharmakyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-10-08 13:21:05.029514+00:00
last_modified: 2023-10-08 13:21:05.029520+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W23566
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23566
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། སྒམ་པོ་པ།
  languages:
  - bo
  author: སྒམ་པོ་པ་བསོད་ནམས་རིན་ཆེན།
statistics:
  ocr_word_mean_confidence_index: 0.9625825913403511
  ocr_word_median_confidence_index: 0.99934584
bases:
  I2175:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2175
      total_pages: 520
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I2175.txt
    statistics:
      ocr_word_median_confidence_index: 0.99921674
      ocr_word_mean_confidence_index: 0.9602625424377063
  I2174:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2174
      total_pages: 558
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2174.txt
    statistics:
      ocr_word_median_confidence_index: 0.998643965
      ocr_word_mean_confidence_index: 0.9590720946214336
  I2176:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2176
      total_pages: 532
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I2176.txt
    statistics:
      ocr_word_median_confidence_index: 0.9997770500000001
      ocr_word_mean_confidence_index: 0.9687919902253405
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
